# Chapter 4: Numpy for Numerical Calculation

## 4.1 Introduction
NumPy (Numerical Python) is an open source Python library that's widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional **ndarray**, and a library of functions that operate efficiently on these data structures.

Python lists are excellent, general-purpose containers. They can be 'heterogeneous', meaning that they can contain elements of a variety of types, and they are quite fast when used to perform individual operations on a handful of elements.

Depending on the characteristics of the data and the types of operations that need to be performed, other containers mau be more appropriate; by exploiting these characteristics, we can improve speed, reduce memory consumption, and offer a high-level syntax for performing a verity of common processing task. NumPy Shines when there are large quantities of "homogeneous" (same type) data to be processed on the CPU.

## 4.2 Installation of NumPy

If we are using Colab or web interface to write code then, we do not require to install any additional library, as its already pre-inbuilded by the developer.

If we have installed **[Anaconda](www.anaconda.org)** then we have NumPy pre-installed. we can check it by running:

pip list

In our **PowerShell** or **Anaconda Prompt** or in **VS Code terminal**.

If we are not using Anaconda system and we have **[Python](www.python.org)** installed, then we need to initialize the Python-pip settings and run:

pip install numpy

In our command Prompt (like **PowerShell** or **Anaconda Prompt** or in **VS Code terminal**). If we are in Linux environment just running this is enough for initialization.

sudo apt-get install Python-numpy ---> Debian System

sudo pacman -Sy Python-numpy --> Arch System or
yay -Sy Python-numpy

Now we can import Numpy in python file by simply writing:

In [57]:
import numpy as np

The code snippet above imports the NumPy library, which is a powerful tool for numerical computing in Python. It provides support for arrays, matrices, and a wide range of mathematical functions. By importing NumPy as 'np', we can use its functions and features with the 'np' prefix, making our code more concise and easier to read.

In [58]:
print(f"Numpy version: {np.__version__}")

Numpy version: 2.3.5


The **__version__** attribute is a conventional way to store a Python package's version within its source code, typically in the top-level. It is a string and serves as a simple way for developers to check an installed library version.

## 4.3 Arrays

**Learning Objective**
By the end of this section, you should be able to:

- Make arrays
- Identify the various array attributes

**Theory**
In computer programming, an array is a structure for storing and retrieving data. We often talk about an arrays as if it were a grid in space, with each cell storing one element of the data. For instance, if each element of the data were a number, we might visualize a 'one-dimensional' array like a list:

    | 1 | 5 | 9 | 8 | 0 |

A two-dimensional array would be like a table:

    | 1 | 5 | 9 | 8 | 0 |
    | 2 | 6 | 8 | 0 | 1 |
    | 3 | 5 | 7 | 9 | 0 |

A three-dimensional array would be like a set of tables, perhaps stacked as though they were printed on seperate pages. In Numpy, this idea generalized to an arbitrary number of dimensions, and so the fundamental array class is called **ndarray**: it represents an "N-dimensional array".

Most NumPy arrays have some restrictions. For instance:

- All elements of the array must be of same data type.
- Once created, the total size of the array can not be changed.
- The shape must be "rectangle", not "jagged"; e.g., each row of two dimensional array must have the same number of columns.

When these conditions are met, NumPy exploits these characteristics to make the array faster, more memory efficient, and more convenient to use than less restrictive data structures.

### 4.3.1 Array fundamentals

Unlike Python lists, Numpy arrays are stored in a continuous block of memory and must contain elements of same data type, making them significantly faster for mathematical operations.

1. Creating Basic Array

    One way to initialize an array is using a Python sequence, such as list. For example:

In [59]:
one_dimensional = np.array([1, 2, 3])
print(f"One dimensional array:\n {one_dimensional}\n")

two_dimensional = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Two dimensional array: \n{two_dimensional}\n")

three_dimensional = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"Three dimensional array: \n{three_dimensional}\n")

One dimensional array:
 [1 2 3]

Two dimensional array: 
[[1 2 3]
 [4 5 6]]

Three dimensional array: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]



2. Indexing and Slicing

    Elements of an array can be accessed in various ways. For instance, we can access an individual element of this arrays as we wold access an element in the original list: using the integer index of the element within square brackets.

In [60]:
# One Dimensional array indexing
one_dimensional[0]


np.int64(1)

In [61]:
# Two Dimensional array indexing
two_dimensional[0]


array([1, 2, 3])

In [62]:
two_dimensional[0][1]

np.int64(2)

In [63]:

# Three Dimensional array indexing
three_dimensional[1]


array([[ 7,  8,  9],
       [10, 11, 12]])

In [64]:
three_dimensional[1][0]


array([7, 8, 9])

In [65]:
three_dimensional[0][1][0]

np.int64(4)

Accessing data in NumPy is very similar to Python lists, but extends to multiple dimensions:

- arr[0,1] : Accesses the element at row 0, column 1.
- arr[:,1] : Accesses all rows in column 1.
- arr[1:3,:] : Accesses rows 1 and 2, and all their columns. 

3. Key Attributes

    Every Numpy array has specific properties that describes it "shape" and data.

    1. **ndim**:The number of dimensions of an array is contained in the **ndim** attribute.

In [66]:
print(f"ndim of one_dimensional: {one_dimensional.ndim}")
print(f"ndim of two_dimensional: {two_dimensional.ndim}")
print(f"ndim of three_dimensional: {three_dimensional.ndim}")

ndim of one_dimensional: 1
ndim of two_dimensional: 2
ndim of three_dimensional: 3


2. **shape**: A tuple showing the size of the array in each dimension. The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

In [67]:
print(f"Shape of one_dimensional: {one_dimensional.shape}")
print(f"Shape of two_dimensional: {two_dimensional.shape}")
print(f"Shape of three_dimensional: {three_dimensional.shape}") 

Shape of one_dimensional: (3,)
Shape of two_dimensional: (2, 3)
Shape of three_dimensional: (2, 2, 3)


3. **size**: The fixed, total number of elements in array is contained in the size attribute.

In [68]:
print(f"size of one_dimensional: {one_dimensional.size}")
print(f"size of two_dimensional: {two_dimensional.size}")
print(f"size of three_dimensional: {three_dimensional.size}")

size of one_dimensional: 3
size of two_dimensional: 6
size of three_dimensional: 12


4. **dtype**: Arrays are typically 'homogeneous', meaning that they contain elements of only one "data type". The data type is recorded in the dtype attribute.

In [69]:
print(f"type of one_dimensional: {one_dimensional.dtype}")
print(f"type of two_dimensional: {two_dimensional.dtype}")
print(f"type of three_dimensional: {three_dimensional.dtype}")

type of one_dimensional: int64
type of two_dimensional: int64
type of three_dimensional: int64


If we combine all,
For example:

In [70]:
strings = np.array([
    ["Hello", "World"],
    ["Night", "Day"],
    ["Data", "Science"]
    ])
print(f"Strings array: \n{strings}\n")
print(f"ndim of strings: {strings.ndim}")
print(f"Shape of strings: {strings.shape}")
print(f"size of strings: {strings.size}")
print(f"type of strings: {strings.dtype}")

Strings array: 
[['Hello' 'World']
 ['Night' 'Day']
 ['Data' 'Science']]

ndim of strings: 2
Shape of strings: (3, 2)
size of strings: 6
type of strings: <U7


4. Array Operations (Vectorization)

One of the best things about NumPy is that you can perform operations on entire arrays without using *for* loops. This is called **Vectorization**.

If you have two arrays, A and B, you can add them simply with A + B. NumPy performs the operation element-wise:

```
C_ij = A_ij + B_ij
```

#### Why is **NumPy** faster than **List**?
Numpy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. This behaviour is called **locality of reference in computer science**. It is optimized to work with latest CPU architectures.

1. speed: NumPy is written in C, so operations are performed at near-hardware speed.
2. Memory: Arrays consume less space than Python lists of lists.
3. Functionality: It provides high-level math functions (Linear Algebra, Fourier transforms, etc) out of the box.

### 4.3.2 Creating ndarray

In addition to **numpy.array()** there are a number of other functions for creating new arrays. As examples,
- **numpy.zeros()** and **numpy.ones()** creates an arrays of 0's and 1's, respectively, with a given length or shape.
-  **numpy.arange()** creates an array without initializing its values to any particular value. 
-  **numpy.linspace()** creates an array that are spaced linearly in a specified interval.

To create a higher dimensional array with these methods, pass a tuple for the shape:

numpy.zeros()

In [71]:
import numpy as np

zeros = np.zeros(10)
zeros


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [72]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

numpy.ones()

In [73]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [74]:
ones = np.ones((3,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

numpy.arange()

In [75]:
range = np.arange(10)
range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

numpy.arange(first number, last number, step size)

In [76]:
range = np.arange(1, 10, 2)
range

array([1, 3, 5, 7, 9])

numpy.empty()

In [77]:
empty = np.empty(2)
empty

array([2.05833592e-312, 2.05833592e-312])

numpy.linspace()

In [78]:
linspace = np.linspace(0, 10, 5)
linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#### Some important NumPy array creation functions:
* Array: Convert input data (list, tuple, array, or other sequence type) to ndarray either by inferring a data type or explicitly specifying a data type; copies the input data by default.
* asarray: Convert input to ndarray, but do not copy if the input is already an ndarray.
* arange: Like the built-in range but returns an ndarray instead of list.
* ones, ones_like: Produces an array of all 1's with the given shape and data type; ones_like takes another array and produces a ones array of the same shape and data_type.
* zeros, zeros_like: Like ones and ones_like but producing arrays of 0's instead.
* empty, empty_like: Creates new arrays by allocating new memory, but do not populate with any values like ones and zeros.
* full, full_like: Produce an array of the given shape and data type with all values set to the indicated "fill value"; full_like takes another array and produces a filled array of the same shape and data type.
* eye, identify: Create a square N x N identity matrix (1s on the diagonal and 0s elsewhere)

### 4.3.4 Data Type in ndarrays
The data type or dtype is a special object containing the information (or metadata, data about data) the ndarray a chunk of memory as a particular type of data:

In [79]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(f"arr1: {arr1}, dtype: {arr1.dtype}")
print(f"arr2: {arr2}, dtype: {arr2.dtype}")

arr1: [1. 2. 3.], dtype: float64
arr2: [1 2 3], dtype: int32


Data types are the source of NumPy's flexibility for interacting with data coming from other system. In most cases, they provide a mapping directly onto an underlying disk or memory representation, which makes it possible to read and write binary streams of data to disk and to connect to code written in low-level language like C or FORTRAN.

There are both **signed** and **unsigned** **integer** types, and may readers will not be familiar with this terminology.

A **signed integer** can represent both positive and negative integers.

A **unsigned integer** can only represent non-zero integers.

For example, int8 (signed 8-bit integer) can represent integer from -128 to 127 (inclusive), while uint8 (unsigned 8-bit integer) can represent 0 through 255.

### 4.3.3 Conversion or Cast
We can explicitly convert or cast an array from one data type to another using ndarray's astype method:

In [80]:
arr1 = np.arange(1, 10)
print(f"arr1: {arr1}, dtype: {arr1.dtype}")
float_arr1 = arr1.astype(np.float64)
print(f"float_arr1: {float_arr1}, dtype: {float_arr1.dtype}")

arr1: [1 2 3 4 5 6 7 8 9], dtype: int64
float_arr1: [1. 2. 3. 4. 5. 6. 7. 8. 9.], dtype: float64


In this example, integers were cast to floating point. If we cast some floating-point numbers to be of integer data type, the decimal part will be truncated:

In [81]:
arr = np.array([3.7, 4.6, 7.7, -1.3, -9.0, 10.1])
print(f"Original array: {arr}")
arr_int = arr.astype(np.int32)
print(f"Array after converting to int32: {arr_int}")

Original array: [ 3.7  4.6  7.7 -1.3 -9.  10.1]
Array after converting to int32: [ 3  4  7 -1 -9 10]


If we have an array of strings representing numbers, we can use astype to convert them to numeric form:

In [82]:
numeric_strings = np.array(['3.2','-7.7', '2.5', '0.0'])
print(f"Original numeric strings array: {numeric_strings}")
numeric_floats = numeric_strings.astype(np.float64)
print(f"Numeric floats array: {numeric_floats}, dtype: {numeric_floats.dtype}")

Original numeric strings array: ['3.2' '-7.7' '2.5' '0.0']
Numeric floats array: [ 3.2 -7.7  2.5  0. ], dtype: float64


📝Note: Be cautious when using numpy.string_type, as string data in NumPy is fixed size and may truncate input without warning. Pandas has more intuitive out-of-the-box behaviour on non-numeric data.

If casting were to fail for some reason (like a string that cannot be converted to float64), a ValueError will be raised. NumPy aliases the Python types to its own equivalent data types.

In [84]:
strings = np.array(['Hello', 'World'])
print(f"Original strings array: {strings}")
strings_int = strings.astype(np.int32)

Original strings array: ['Hello' 'World']


ValueError: invalid literal for int() with base 10: np.str_('Hello')

## 4.4 Arithmetic Operation and Broadcasting With NumPy Arrays
Arrays are important becaues they enable you to express batch operations on data without writing any for loops. NumPy user call this vectorization. Any arithmetic operation between equal-size arrays apply the operation element-wise:

In [ ]:
arr1 = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
],dtype=np.float64)
print(f"Original arr1: \n{arr1}")

Original arr1: 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
arr1 * arr1

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]])

In [ ]:
arr1 - arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Arithmetic operations with scalars propagate the scalar argument to each element in the array:

In [ ]:
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

In [ ]:
arr1 ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]])

Comparisons between arrays of the same size yield Boolean arrays:

In [ ]:
arr2 = np.array([
    [0. , 4., 1.],
    [7., 2., 12.],
    [3., 9., 15. ]
])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.],
       [ 3.,  9., 15.]])

In [ ]:
arr2 > arr1

array([[False,  True, False],
       [ True, False,  True],
       [False,  True,  True]])

Evaluating operations between differently sized array is called **Broadcasting**.

## 4.5 Indexing and Slicing
NumPy array indexing is a deep topic, as there are many ways you may want to select a subset of your data or individual elements. One-dimensional arrays are simple; on the surface they act similarly to Python lists:

In [85]:
arr = np.arange(10)
print(f"Original array: {arr}")

Original array: [0 1 2 3 4 5 6 7 8 9]


In [86]:
arr[5:8]

array([5, 6, 7])

In [87]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

As we can see, if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is propagated (or broadcast henceforth) to the entire selection.

📝 Note: An important first distinction Python's built-in lists is that array slices are views on the orginal array. This means that the data is not copied, and any modifications to the view will be reflected in the source array.

To give an example of this;

In [88]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

Now, When we change the value of **arr_slice**, the mutations are reflected in the orginal array arr:

In [89]:
arr_slice[1] = 144523
arr_slice

array([    12, 144523,     12])

In [90]:
arr

array([     0,      1,      2,      3,      4,     12, 144523,     12,
            8,      9])

The original array was modified when we changed the slice because the slice is a view of the original array, not a copy.

The "bare" slice [:] will assign to all values in an array:

In [91]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

If you are new to NumPy, you might be suprised by this, especially if you have used other array programming languages that copy data more eagerly. As NumPy has been designed to be able to work with very large arrays, you could imagine performance and memory problems if NumPy insisted on always copying data.

👉: If you want a copy of a slice of an ndarray instead of view, you will need to explicitly copy the array - for example, arr[5:8].copy() or numpy.copy(arr[5:8]). 

In [92]:
copied_data = arr[5:8].copy()
copied_data

array([64, 64, 64])

In [93]:
copied_data[1] = 1233
print(f"copied_data after modification: {copied_data}")
print(f"Original array after modifying copied_data: {arr}")

copied_data after modification: [  64 1233   64]
Original array after modifying copied_data: [ 0  1  2  3  4 64 64 64  8  9]


See, No changes when you copy data from the orginal source.

With higher dimensional arrays, we have many more options. In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays:

In [95]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [96]:
arr2d[2]

array([7, 8, 9])

Thus, individual elements can be accessed recursively. But that is a bit too much work, so you can pass a comma-seperated list of indices to select individual element. So these are equivalent:

In [97]:
arr2d[0][2]

np.int64(3)

In [98]:
arr2d[0,2]

np.int64(3)

In multidimensional arrays, if we omit later indices, the returned object will be a lower dimensional ndarray consisting of all the data along the higher dimensions. So in the 2 X 2 X 3 array arr3d:

In [99]:
arr3d = np.array(np.ones((2,2,3)))
arr3d

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

arr3d[0] is a 2 X 3 array

In [100]:
arr3d[0].shape

(2, 3)

In [101]:
arr3d[0]

array([[1., 1., 1.],
       [1., 1., 1.]])

Both scalar values and arrays can be assigned to arr3d[0]:

In [102]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42., 42., 42.],
        [42., 42., 42.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [103]:
arr3d[0] = old_values
arr3d

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

Similarly, arr3d[1,0] gives us all of the values whose indices start with (1,0), forming a one-dimensional array:

In [104]:
arr3d[1,0]

array([1., 1., 1.])

In [105]:
arr3d[1,0] = 22
arr3d

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[22., 22., 22.],
        [ 1.,  1.,  1.]]])

📝 Note: In all of these cases where subsections of the array have been selected, the returned arrays are views. 

📝 NoteL This multidimensional indexing syntax for NumPy arrays will not work with regular Python objects, Such as lists of lists.

### 4.5.1 Boolean Indexing
let's consider an example where we have some data in an array and an array of names with duplicates:

In [106]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [107]:
data = np.array([
    [4,7],
    [8,5],
    [-12,-4],
    [-5,6],
    [6,-5],
    [0,-8],
    [0,1]])
data

array([[  4,   7],
       [  8,   5],
       [-12,  -4],
       [ -5,   6],
       [  6,  -5],
       [  0,  -8],
       [  0,   1]])

Suppose each name corresponds to a row in the data array and we wanted to select all the rows with the corresponding name "Bob". Like arithmetic operations, comparasions (==) with arrays are also vectorized. Thus, comparing names with the string "Bob" yields a Boolean array:

In [108]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

This Boolean array can be passed when indexing the array:

In [109]:
data[names == 'Bob']

array([[ 4,  7],
       [-5,  6]])

The boolean array must be of same length (len(data) && len(names) == True) as the arrays axis it's indexing. You can even mix and match Boolean arrays with slices or integers (or sequences of integers).

In these example, we will select from the rows where names == 'Bob' and index the columns, too:

In [112]:
data[names == 'Bob', 1:]

array([[7],
       [6]])